theme: jekyll-theme-cayman
google_analytics: UA-22750309-1
title: Joshua Edgcombe
description: Electrical Engineer & Software Developer

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"